### ISSUE TITLE
typealias AbstractVMF is not fixed in tagged versions

### ISSUE THREAD

**Issue by henryk-modzelewski** [simonbyrne/InplaceOps.jl#15]
I looks like the deprecated 'typealias AbstractVMF' is fixed on the master branch, but not in the most recent tagged version. Hence it still throws a warning with typical installation.

**Comment by garrison** [comment]
Indeed, there was never a release that ran on julia 0.6 without warnings.  The package is also completely broken on julia 0.7 as a result.  (Of course, the master branch has issues as well on julia 0.7, so it's not just the lack of release that is holding up 0.7 support.)  It might be nice to do a release immediately for julia 0.6 before restructuring for 0.7 and higher, as much of the underlying in-place multiplication interface changed between 0.6 and 0.7.

**Comment by simonbyrne** [comment]
Just tagged v0.2.0 which is compatible with 0.6. Working on 0.7/1.0 now.

**Comment by simonbyrne** [comment]
Now revamped and working on 0.7.
