### ISSUE TITLE
missing ops?

### ISSUE THREAD

**Issue by denizyuret** [simonbyrne/InplaceOps.jl#3]
Hi Simon: Some operations seem to be missing from the implementation:

```
julia> @in1! a + b
ERROR: add! not defined

julia> @in1! a - b
ERROR: sub! not defined
```

Their broadcasting versions `@in1! a .+ b; @in1 a .- b` work.

**Comment by simonbyrne** [comment]
Ah, yes. I didn't implement the non-broadcasting versions as all the cases could be handled by the broadcasting operators. I'll try to fix this when I get a chance.

**Comment by wildart** [comment]
Sparse matrices are not covered as well.
```julia
julia> S = sprand(3,3,0.3)
julia> T = similar(S)
julia> @into! T = S' * S;
ERROR: `At_mul_B!` has no method matching At_mul_B!(::SparseMatrixCSC{Float64,Int64}, ::SparseMatrixCSC{Float64,Int64}, ::SparseMatrixCSC{Float64,Int64})
 in mul! at /home/art/.julia/v0.3/InplaceOps/src/InplaceOps.jl:54
```

**Comment by simonbyrne** [comment]
I have drastically reduced the scope of this package. Broadcasting should now use the `@.` macro.
