### ISSUE TITLE
subarrays

### ISSUE THREAD

**Issue by denizyuret** [simonbyrne/InplaceOps.jl#5]
Hi Simon: the macros do not seem to work with array slices or subarrays:
```
x=zeros(100)
@in1! x[1:10] .+ 3  # x is still zeros
xx=sub(x,1:10)
@in1! xx .+ 3   # gives error
```
Do you have any suggestions?  Maybe Devectorize?

**Comment by simonbyrne** [comment]
I've just pushed a patch: it should now work for subarrays. Slices are a bit trickier: I'll probably wait until 0.4 is released to have a look at the new Array Views (which I haven't really looked at in detail).
