### ISSUE TITLE
Possiblity of adding support for += and -=.

### ISSUE THREAD

**Issue by KristofferC** [simonbyrne/InplaceOps.jl#6]
Would it be possible (desireable) to transform `@into! u += a * X * v` where `a` is a number to

``` julia
BLAS.gemm!('N', 'N' ,a, X, v, 1.0, u)
```

The same could be done for `-=` of course.

I could try implement it and submit a PR.

**Comment by simonbyrne** [comment]
Yes, this is certainly a good idea, please open a PR.

**Comment by KristofferC** [comment]
I realize that quite a lot of logic need to be added because of the fact that `gemm_wrapper!` is hard coded to call BLAS with `a=0` and `b=1` as coefficients to `u = a*u +  b * X * v`.

If only all the `A_x_B` version took `a` and `b` as parameters and defaulted them to `0` and `1`.

**Comment by KristofferC** [comment]
I realize I basically have to replicate all of the dispatching that the `A_mul_B` functions are currently doing but add my own `a` and `b` to them. Since this requires a bit more time investment than I currently have I will close this and maybe tackle it again when I have more time or when Base has a bit nicer interface for it.

**Comment by simonbyrne** [comment]
Probably a good idea to leave the issue open, maybe someone else (perhaps even me someday) will fix this.

**Comment by KristofferC** [comment]
So I took a very small step towards this. This is the first time I have used meta programming and macros at all so it is probably horrible. Right now it only works for matrix multiplication. Since I am a complete newbie at macro I used MacroTools to help: https://github.com/one-more-minute/MacroTools.jl

Here is the code https://gist.github.com/KristofferC/ec880377299b2f04836e

And some macroexpansions:

```julia
julia> macroexpand(:(@into_plus! C += 5.0 * A' * B.'))
quote  # none, line 27:
    BLAS.gemm!('C','T',5.0,A,B,1.0,C)
end

julia> macroexpand(:(@into_plus! C += A' * B.'))
quote  # none, line 27:
    BLAS.gemm!('C','T',1.0,A,B,1.0,C)
end

julia> macroexpand(:(@into_plus! C += A * B'))
quote  # none, line 27:
    BLAS.gemm!('N','C',1.0,A,B,1.0,C)
end
```

As I said before, the problem is that `Ax_mul_Bx` and company are useless because none of them define the `\alpha` and `\beta` so I need to go for the direct blas call.

**Comment by lopezm94** [comment]
I'm making a package for using BLAS with sugar, for example at the moment `gemm!` looks like this:

```julia
julia> macroexpand(:(@gemm! C = alpha*A*B + beta*C))
:(Base.LinAlg.BLAS.gemm!('N','N',alpha,A,B,beta,C))

julia>  macroexpand(:(@gemm! C = beta*C + 1.5*A*B'))
:(Base.LinAlg.BLAS.gemm!('N','T',1.5,A,B,beta,C))

julia> macroexpand(:(@gemm! C = 3.4*C + alpha*A'*B'))
:(Base.LinAlg.BLAS.gemm!('T','T',alpha,A,B,3.4,C))
```

Adding the `@gemm! C += alpha*A*B` would be straight forward, the API for the package is still in discussion. If you are interested check [here](https://github.com/lopezm94/SugarBLAS.jl/issues/1)
