### ISSUE TITLE
Tag new version.

### ISSUE THREAD

**Issue by KristofferC** [simonbyrne/InplaceOps.jl#8]
Hi,

Could it maybe be possible to tag a new version so that the deprecation fix gets included. I am using this in another package that a few students are using and they get confused about the deprecation warning :P.

I know it is really boring and I would do it myself for you if I could heh.

**Comment by simonbyrne** [comment]
Done.

I've also added you as a collaborator, so you have commit access, and can tag versions in future.

**Comment by KristofferC** [comment]
Thanks a bunch!
